version: "3"
services:
    nginx:
        build: nginx/
        restart: always
        depends_on:
          - php-fpm
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./www:/www
          - ./var/logs:/var/log/nginx
          - ./nginx/conf/conf.d:/etc/nginx/conf.d
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/ssl:/etc/nginx/ssl
          - /etc/localtime:/etc/localtime
        networks:
          - default
    php-fpm:
        build: php-fpm/
        restart: always
        depends_on:
          - mysql
          - redis
        volumes:
          - ./www:/www
          - ./var/run:/var/run
          - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
          - /etc/localtime:/etc/localtime
        networks:
          - default
    mysql:
        build: mysql/
        restart: always
        ports:
          - "3306:3306"
        environment:
          - TZ=Asia/Shanghai
          - MYSQL_DATABASE=test
          - MYSQL_ROOT_PASSWORD=huotu@666
        volumes:
          - ./var/run:/run/mysqld
          - ./mysql/data:/var/lib/mysql
          - ./mysql/conf/my.cnf:/etc/my.cnf
          - /etc/localtime:/etc/localtime
        networks:
          - default
        command:
          --default-authentication-plugin=mysql_native_password
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_general_ci
    redis:
        build: redis/
        restart: always
        volumes:
          - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
          - ./var/logs/redis.log:/var/log/redis.log
          - /etc/localtime:/etc/localtime
        ports:
          - "6379:6379"
        networks:
          - default
networks:
    default:
        driver: bridge
